whiptail detection

diff --git a/smlinux b/smlinux
--- a/smlinux
+++ b/smlinux
@@ -3,7 +3,7 @@
 # Other distros edit config file when prompted to change Linux= to command to get your dependencies.
 # Dependencies for many distros are listed on the github FAQ.  Please let me know if incorrect
 # or if you have another distro to add.
-TIMESTAMP=2020-1001-1937
+TIMESTAMP=2020-1002-1118
 
 domake(){
 #Here We go & music to build to
@@ -504,7 +504,10 @@ fi
 }
 
 doconfig(){
-if(whiptail --title "Build Options" --yesno "$(cat "$SMLINUX"/smlinuxcfg.txt)" 28 77 --yes-button "Edit Options" --no-button "Proceed" --defaultno); then
+if ! command -v whiptail &> /dev/null
+then
+    echo "COMMAND could not be found"
+elif (whiptail --title "Build Options" --yesno "$(cat "$SMLINUX"/smlinuxcfg.txt)" 28 77 --yes-button "Edit Options" --no-button "Proceed" --defaultno); then
 	whiptail --title "smlinux paused until you exit editor" --msgbox "Your configuration file will open in a text editor.\n\nWhen you exit your editor, smlinux will continue.\n\nFor first build, default options which include community enhancements are reccommended.\n\nIf you mess up your settings,\nrun smlinux reset to restore to latest defaults." 16 60 2>&1
 	editconfig	
 fi
@@ -888,6 +891,8 @@ if [ ! -f ~/.smlinuxUpdate ]; then
 				echo smlinux exiting incomplete.
 				exit
 			fi
+		else
+			echo smlinux succefully added to path.
 		fi
 		chmod +x "$PATHDIR"/smlinux
 		cd "$LAUNCH_DIR"
@@ -1231,7 +1236,6 @@ elif [ -f ~/.smlinuxUpdate ]; then
 	echo Script Update Complete.
 else	     # The real start, the rest was script preperation and setup. 
 	echo '/---------------------------'"$TIMESTAMP"'------------------------------------\'
-	echo "|                                                                             |"
 	echo "|     Super Mario 64 Install * Build * Update Script for Linux and MacOS      |"
 	echo "|                                                                             |"
 	echo "|        Command Line Usage: smlinux <command> <options>                      |"
@@ -1249,8 +1253,7 @@ else	     # The real start, the rest was script preperation and setup.
 	echo "|   purge: Deletes all files obtained or created by smlinux including sm64    |"
 	echo "|    help: Display this message and the URL for github faq                    |"
 	echo "|                                                                             |"
-	echo "| Options   --config   prompt to edit configuration file before build/update  |"
-	echo "|           --sgi      aquire and apply Render96 SGI models (V 1.3 or co-op)  |"
+	echo "| Options:  --sgi  aquire and apply Render96 SGI models (V1.3 or co-op)       |"
 	echo "-------------------------------------------------------------------------------"
 	if [ "$1" = "--help" ] || [ "$1" = "-help" ] || [ "$1" = "help" ] || [ "$1" = "-h" ]; then
 		echo More help at https://github.com/enigma9o7/smlinux#frequently-asked-questions
@@ -1261,9 +1264,13 @@ else	     # The real start, the rest was script preperation and setup.
 	if [ ! -d "$SMLINUX"/.git ] || [ "$DEPENDS" = 1 ] || [ "$1" = "depends" ]; then
 		if [ "$OSX_BUILD" = 1 ]; then
 			echo "Installing dependencies for MacOS..."
-			if [ ! -f /usr/local/bin/brew ]; then
-				echo Installing Homebrew package manager...
+			if ! command -v brew &> /dev/null; then
+    			echo Installing Homebrew package manager...
 				bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
+			fi
+			if ! command -v brew &> /dev/null; then
+				echo FATAL ERROR Could not install homebrew, thus cannot install other stuff.  
+				endnow
 			fi
 			brew install libxdg-basedir coreutils go wget newt nano unzip unrar p7zip python3 
 			brew install git gcc@9 mingw-w64 sdl2 pkg-config glew glfw3 libusb audiofile 
