better handle first install with python script

diff --git a/smlinux b/smlinux
--- a/smlinux
+++ b/smlinux
@@ -5,7 +5,7 @@
 # Dependencies for many distros are listed on the github FAQ.  
 # Please let me know if incorrect or if you have another distro to add.
 # Script updates from github.com/enigma9o7/smlinux unless AutoUpdate=0.
-TIMESTAMP=2020-1114-1018
+TIMESTAMP=2020-1114-1317
 
 domake(){
 if [ -d "$BASEPATH"/"$PRESET"/build/"$VERSION"_"$TARGET" ] && [ ! "$COMMAND" = "rebuild" ]; then
@@ -800,7 +800,7 @@ fi
 }
 
 editconfig(){
-if [ "`pip3 list --format=columns | grep numpy`" = "" ] || ([ "$TARGET_OSX" = 1 ] && [ "`pip3 list --format=columns | grep PyQt5`" = "" ]) ; then
+if ! command -v pip3 &> /dev/null || [ ! -f "$SMLINUX"/config.py ] || [ "`pip3 list --format=columns | grep numpy`" = "" ] || ([ "$TARGET_OSX" = 1 ] && [ "`pip3 list --format=columns | grep PyQt5`" = "" ]) ; then
 	EDITORS=nano:kate:epad:gedit:notepadqq:bluefish:geany:lime:medit:leafpad:pico:micro:jed:emacs:vim:vi
 	IFS=":"
 	for editor in $EDITORS; do
@@ -1580,7 +1580,7 @@ elif command -v whiptail &> /dev/null; then
 		OP1="--noweb"
 	fi
 else
-	pinkecho Warning: Newt/Whiptail is not installed so no menu will be offered.
+	pinkecho Warning: Newt Whiptail is not installed so no menu will be offered.
 	COMMAND=help
 	OP1="--noweb"	
 fi
@@ -1605,7 +1605,7 @@ if [ ! -f "$SMLINUX"/smlinuxcfg.txt ] && [ -f "$SHARE"/sm64pc/smlinuxcfg.txt ]; 
 	# update paths from old versions of smlinux that shared sm64pc folder for configfile
 	pathupdate
 fi
-if command -v pip3 &> /dev/null; then # new dependency for python config GUI
+if command -v pip3 &> /dev/null; then # new dependencies for python config GUI
 	if [ "`pip3 list --format=columns | grep numpy`" = "" ]; then
 		echo Installing Numpy for python config editor...
  		pip3 install numpy 
@@ -1751,30 +1751,30 @@ elif [ "$COMMAND" = "upgrade" ]; then
 else   # The real start, the rest was script preperation and setup. 
 	tput setab 0  # black background
 	tput setaf 6  # cyan text
-	echo '/------------------------------'"$TIMESTAMP"'--------------------------------\'
-	echo "|                                                                            |"
-	echo "|     Super Mario 64 Install * Build * Update Script for Linux and macOS     |"
-	echo "|                                                                            |"
-	echo "|               Command Line Usage: smlinux <command> <options>              |"
-	echo "| Commands                                                                   |"
-	echo "|  update: Update existing sm64 source & build (preserves modifications)     |"
-	echo "|   build: Get/reset sm64 source repository & build (renames existing folder)|"
-	echo "|   clone: Get/reset sm64 source repository & extract rom (no addons/build)  |"
-	echo "|  config: Opens smlinuxcfg.txt in a text editor (without building)          |"
-	echo "|   reset: Resets smlinux configuration file to default settings             |"
-	echo "| depends: Install dependencies (automatic during smlinux installation)      |"
-	echo "| upgrade: Upgrade smlinux to latest version from github (without building)  |"
-	echo "|   purge: Delete all files obtained or created by smlinux including sm64    |"
-	echo "|    help: Display all smlinux commands and options plus open faq url        |"
+	echo '/------------------------------'"$TIMESTAMP"'---------------------------\'
+	echo "|                                                                       |"
+	echo "|  Super Mario 64 Install * Build * Update Script for Linux and macOS   |"
+	echo "|                                                                       |"
+	echo "|               Command Line Usage: smlinux <command> <options>         |"
+	echo "| Commands                                                              |"
+	echo "|  update: Update existing sm64 source & build (preserves modifications)|"
+	echo "|   build: Get/reset sm64 source repo & build (renames existing folder) |"
+	echo "|   clone: Get/reset sm64 source repo & extract rom (no addons/build)   |"
+	echo "|  config: Opens smlinuxcfg.txt in a text editor (without building)     |"
+	echo "|   reset: Resets smlinux configuration file to default settings        |"
+	echo "| depends: Install dependencies (automatic during smlinux installation) |"
+	echo "| upgrade: Upgrade smlinux to latest version from github (no build)     |"
+	echo "|   purge: Remove all files and folders obtained or created by smlinux  |"
+	echo "|    help: Display all smlinux commands and options plus open faq url   |"
 	if [ "$COMMAND" = "help" ]; then
-		echo "| rebuild: rebuild an existing or previously failed build with no changes    |"
-		echo "|                                                                            |"
-		echo "| Options:   --hd  install HD add-ons (ignore EnableHD=0/UpgradeHD=0)        |"
-		echo "|           --sgi  install Render96 SGI model pack (ignore InstallR96=0)     |"
-		echo "|        --config  prompt to edit config file before build (ignore CONFIG=0) |"
-		echo "|       --depends  install dependencies before build                         |"
-		echo "|                                                                            |"
-		echo "------------------------------------------------------------------------------"
+		echo "| rebuild: rebuild existing or previously failed build with no changes  |"
+		echo "|                                                                       |"
+		echo "| Options:   --hd  install HD add-ons (ignore EnableHD=0/UpgradeHD=0)   |"
+		echo "|           --sgi  install Render96 SGI model pack (ignore InstallR96=0)|"
+		echo "|        --config  prompt to edit config before build (ignore CONFIG=0) |"
+		echo "|       --depends  install dependencies before build                    |"
+		echo "|                                                                       |"
+		echo "-------------------------------------------------------------------------"
 		tput setaf 7 # white text
 		if [ "$OP1" = "--noweb" ]; then
 			exit
@@ -1784,8 +1784,8 @@ else   # The real start, the rest was script preperation and setup.
 		"$OPEN" "https://github.com/enigma9o7/smlinux#frequently-asked-questions"
 		exit
 	else
-		echo "|                                                                            |"
-		echo "------------------------------------------------------------------------------"
+		echo "|                                                                       |"
+		echo "-------------------------------------------------------------------------"
 	fi
 	greenecho [1] Preparing for "$COMMAND"...
 	if [ ! -d "$SMLINUX"/.git ] || [ "$DEPENDS" = 1 ] || [ "$COMMAND" = "depends" ]; then
