install homebrew pack-man for macos

diff --git a/smlinux b/smlinux
--- a/smlinux
+++ b/smlinux
@@ -3,7 +3,7 @@
 # Other distros edit config file when prompted to change Linux= to command to get your dependencies.
 # Dependencies for many distros are listed on the github FAQ.  Please let me know if incorrect
 # or if you have another distro to add.
-TIMESTAMP=2020-0927-1824
+TIMESTAMP=2020-0928-2142
 
 domake(){
 #Here We go & music to build to
@@ -153,13 +153,13 @@ elif [ "$TARGET" = "dos" ]; then
 fi
 echo
 echo smlinux is complete. 
-echo smlinux internal timestamp:
-echo "$TIMESTAMP".
+echo smlinux internal timestamp "$TIMESTAMP".
 echo "$GIT" last commit:
 cd "$BASEPATH"/"$PRESET"
 git log -1 --format=%cd
 echo Please exit or close this terminal window!
 echo
+exit
 }
 
 
@@ -294,7 +294,9 @@ echo '# PRESET supports: sm64pc sm64ex render96ex r96proto cheaterex
 # AND: sm64dos sm64-portweb sm64exweb sm64-port-android-base androidex 
 PRESET=sm64ex
 InstallHD=1
-# [ sm64ex and its forks ] 
+# set MAXJOBS=n to limit cpu threads used, i.e. MAXJOBS=1 or MAXJOBS=7
+MAXJOBS=
+# [ options for sm64ex and its forks ] 
 BETTERCAMERA=1
 NODRAWINGDISTANCE=1
 TEXTURE_FIX=1
@@ -303,14 +305,14 @@ DISCORDRPC=1
 # RENDER_API supports GL (2.1+) or GL_LEGACY (1.1+)
 RENDER_API=GL
 TEXTSAVES=0
-# [ sm64ex-coop ]
+# [ options for sm64ex-coop only ]
 IMMEDIATELOAD=1
-# [ render96ex ]
+# [ options for render96ex only ]
 LEGACY_RES=1
-# [ Android ]
+# [ options for Android only ]
 TOUCH_CONTROLS=1
 ARMONLY=1
-# [ DOS ]
+# [ options for DOS only ]
 ENABLE_OPENGL_LEGACY=1
 # DOS_GL Supports dmesa (glide) or osmesa
 DOS_GL=osmesa
@@ -318,8 +320,6 @@ ENABLE_OPENGL_LEGACY=1
 # [ Advanced Settings ]
 # VERSION supports us jp eu (must correspond to rom version)
 VERSION=us
-# set MAXJOBS=n to limit cpu threads used, i.e. MAXJOBS=1 or MAXJOBS=7
-MAXJOBS=
 # Set CONFIG=0 If you do not want to be automatically prompted before building.
 CONFIG=1
 # BASEPATH must exist and is where folders for each repo will be placed
@@ -328,16 +328,17 @@ BASEPATH=$HOME
 UpdateHD=1
 # set DEBUG=1 if you want to make a debug build for some odd reason
 DEBUG=0
+# Set AutoUpdate=0 to prevent smlinux updating itself
+AutoUpdate=1
 TARGET_WEB=0
 TARGET_RPI=0
 OSX_BUILD=0
-# [ These settings are ignored if PRESET is known ]
+# [ GIT and BRANCH are ignored if PRESET is known ]
 GIT=sm64pc/sm64ex
 BRANCH=nightly
 # [ Linux must be set to command appropriate to your distribution. See FAQ. ]
-Linux="sudo apt install -y build-essential bsdmainutils wget git python3 libaudiofile-dev libglew-dev libsdl2-dev binutils libusb-1.0-0-dev libzstd-dev python3-pip p7zip-full mplayer"
-# Set AutoUpdate=0 to prevent smlinux updating itself
-AutoUpdate=1' > "$SMLINUX"/smlinuxcfg.txt
+# Linux command is only called during first install and is not used for MacOS
+Linux="sudo apt install -y build-essential bsdmainutils wget git python3 libaudiofile-dev libglew-dev libsdl2-dev binutils libusb-1.0-0-dev libzstd-dev python3-pip p7zip-full mplayer"' > "$SMLINUX"/smlinuxcfg.txt
 }
 
 loadconfig(){
@@ -1224,7 +1225,7 @@ if [ "$1" = "--purge" ] || [ "$1" = "purge" ]; then
         exit
 fi
 
-if [ -f "$1" ] || [ -f "$LAUNCH_DIR"/"$1" ] || ( [ -f "$SMLINUX"/baserom."$VERSION".z64 ] && ( [ "$1" = "build" ] || [ "$1" = "update" ]  )); then
+if [ -f "$1" ] || [ -f "$LAUNCH_DIR"/"$1" ] || ( [ -f "$SMLINUX"/baserom."$VERSION".z64 ] && ( [ "$1" = "build" ] || [ "$1" = "update" ] || [ "$1" = "clone" ] )); then
 	if [ -f ~/.smlinuxUpdate ]; then 
 		rm ~/.smlinuxUpdate
 		echo Script Update Complete.
@@ -1236,11 +1237,13 @@ if [ -f "$1" ] || [ -f "$LAUNCH_DIR"/"$1" ] || ( [ -f "$SMLINUX"/baserom."$VERSI
 				sudo apt update
 			fi
 			if [ "$OSX_BUILD" = 1 ]; then
+				echo "[1] Installing dependencies for MacOS..."
+				if [ ! -f /usr/local/bin/brew ]; then
+					echo Install Homebrew package manager
+					bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
+				fi
 				brew install libxdg-basedir coreutils git wget nano mingw-w64 gcc@9 sdl2 pkg-config glew glfw3 libusb audiofile unzip 7zip unrar
-				alias gcc='gcc-9'
-				alias cc='gcc-9'
-				alias g++='g++-9'
-				alias c++='c++-9'
+				alias gcc='gcc-9';alias cc='gcc-9';alias g++='g++-9';alias c++='c++-9'
 			else
 				$Linux
 			fi
@@ -1267,6 +1270,9 @@ if [ -f "$1" ] || [ -f "$LAUNCH_DIR"/"$1" ] || ( [ -f "$SMLINUX"/baserom."$VERSI
 		elif [ "$TARGET" = "dos" ]; then
 			echo "[1] Loading djgpp for DOS Target..."
 			dodos
+		elif [ "$OSX_BUILD" = 1 ]; then
+			echo "[1] This is not first build, skipping MacOS dependencies..."
+			alias gcc='gcc-9';alias cc='gcc-9';alias g++='g++-9';alias c++='c++-9'
 		else
 			echo "[1] This is not first build, skipping dependencies..."
 		fi
@@ -1305,7 +1311,7 @@ if [ -f "$1" ] || [ -f "$LAUNCH_DIR"/"$1" ] || ( [ -f "$SMLINUX"/baserom."$VERSI
 				echo "ERROR: Specified file is not original Super Mario 64 ROM image or VERSION= set wrong."
 				echo
 				exit
-			elif [ "$1" = "update" ] || [ "$1" = "build" ]; then
+			elif [ "$1" = "update" ] || [ "$1" = "build" ] || [ "$1" = "clone" ]; then
 				echo "ERROR: Must provide valid path/filename to Super Mario 64 romfile."	
 				echo
 				echo smlinux exiting incomplete.  Please specify romfile.
@@ -1326,33 +1332,33 @@ if [ -f "$1" ] || [ -f "$LAUNCH_DIR"/"$1" ] || ( [ -f "$SMLINUX"/baserom."$VERSI
 	fi
 else
 	echo '/---------------------------'"$TIMESTAMP"'------------------------------------\'
-	echo "|                                                                             |"
-	echo "|      Super Mario 64 Install * Build * Update Script for Linux               |"
+	echo "|     Super Mario 64 Install * Build * Update Script for Linux and MacOS      |"
 	echo "|                                                                             |"
 	echo "| Installation & First Build: bash smlinux <romfile>                          |"
-	echo "|  for example:                                                               |"
-	echo "| bash smlinux ~/roms/sm64.n64  or  bash smlinux \"Super Mario 64 (U) [!].z64\" |"
+	echo "|                for example: bash smlinux ~/roms/sm64.n64                    |"
+	echo "|                         or: bash smlinux \"Super Mario 64 (U) [!].z64\"       |"
 	echo "|                                                                             |"
 	echo "| Normal Usage: smlinux <command> <options>                                   |"
+	echo "|  for example: smlinux update                                                |"
 	echo "|                                                                             |"
 	echo "| Commands:                                                                   |"
-	echo "|  update: Updates source & rebuilds, preserving mods and external resources  |"
-	echo "|  build:  Gets new source from github and builds. (Renames existing folder)  |"
-	echo "|  config: Opens smlinuxcfg.txt in text editor without building               |"
-	echo "|  reset:  Resets smlinux configuration file to default settings              |"
-	echo "|  purge:  Removes all files created by this script, including sm64           |"
+	echo "|   build:  Gets new source from github and builds (renames existing folder)  |"
+	echo "|   update: Updates source & rebuilds, preserving mods and external resources |"
+	echo "|   config: Opens smlinuxcfg.txt in a text editor (without building)          |"
+	echo "|   reset:  Resets smlinux configuration file to default settings             |"
+	echo "|   clone:  Clones sm64 repository and extracts rom (without addons or build) |"
+	echo "|   purge:  Deletes all files obtained or created by smlinux including sm64   |"
 	echo "|                                                                             |"
-	echo "| Options: --depends  reinstall dependencies                                  |"
-	echo "|          --config   prompt to edit configuration file before build          |"
-	echo "|          --hd       aquire & apply upscale enhancements (see FAQ)           |"
-	echo "|          --sgi      aquire and apply Render96 SGI models (V 1.3 or co-op)   |"
+	echo "| Options:  --depends  install dependencies                                   |"
+	echo "|           --config   prompt to edit configuration file before build/update  |"
+	echo "|           --sgi      aquire and apply Render96 SGI models (V 1.3 or co-op)  |"
 	echo "-------------------------------------------------------------------------------"
 	if [ "$1" = "--help" ] || [ "$1" = "-help" ] || [ "$1" = "help" ] || [ "$1" = "-h" ]; then
-		echo
+		echo More help at https://github.com/enigma9o7/smlinux#frequently-asked-questions
 	elif [ -f "$SMLINUX"/baserom."$VERSION".z64 ]; then
-		echo "ERROR: You must specify update, build, config, reset or purge."
+		echo "ERROR: You must specify one of the listed commands."
 	else 
-		echo "ERROR: Must provide valid path/filename to Super Mario 64 romfile."	
+		echo "ERROR: You must specify valid path/filename to Super Mario 64 romfile."	
 	fi
 	exit
 fi
@@ -1552,7 +1558,6 @@ if [ "$1" = "-u" ] || [ "$1" = "--update" ] || [ "$1" = "update" ] || [ "$1" = "
 		sleep 10
 	fi
 	theend
-	exit
 fi
 if [ -d "$BASEPATH"/"$PRESET" ]; then
 	if [ ! "$ANDROID" = 0 ]; then
@@ -1609,7 +1614,9 @@ else
 	cd "$BASEPATH"/"$PRESET"
 	./extract_assets.py "$VERSION"
 fi
-
+if [ "$1" = "clone" ]; then
+	theend
+fi
 echo
 echo [5] Applying Community Enhancements...
 echo
